version: 2

models:
  - name: customer_clean

    columns :

     - name: customer_id 
       tests: 
          - not_null
          - unique 

     - name: city  
       tests:
          - not_null
     - name: email 
       tests: 
          - unique
       
          
